export const SOURCES=[
['ZAP/VivaReal','grande'],['OLX','grande'],['Imovelweb/Wimoveis','grande'],['Chaves na Mão','grande'],['Lopes','grande'],['Loft','grande'],['QuintoAndar','grande'],['MGF','regional'],['Zona Leste Imóveis','regional'],['Nestoria','regional'],['Trovit','regional'],['Properati','regional'],['Imobiliária regional 1','regional'],['Imobiliária regional 2','regional']
].map(([name,type],i)=>({id:i+1,name,type,status:'pendente',count:0,url:'',notes:''}));

export function normalizeText(v=''){return String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/\bR\.?\b/g,'RUA').replace(/\bAV\.?\b/g,'AVENIDA').replace(/\s+/g,' ').trim()}
export function money(v){return Number(v||0)}
export function mapsLink(p){if(p.latitude&&p.longitude)return `https://www.google.com/maps/search/?api=1&query=${p.latitude},${p.longitude}`;const q=[p.logradouro,p.numero,p.bairro,p.cidade,p.uf].filter(Boolean).join(', ');return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`}
export function canonicalize(p,i=0){const a=money(p.area_terreno_m2);const price=money(p.preco);return {...p,id_canonico:p.id_canonico||`P-${Date.now()}-${i}`,logradouro:p.logradouro||'',numero:p.numero||'',bairro:p.bairro||'',cidade:p.cidade||'',uf:p.uf||'SP',area_terreno_m2:a,preco:price,preco_m2:a?price/a:0,geo_precisao:p.geo_precisao||'NAO_GEOCODIFICADO',data_consulta:p.data_consulta||new Date().toISOString(),status_anuncio:p.status_anuncio||'ATIVO',flag_desatualizado:!!p.flag_desatualizado,dedup_status:p.dedup_status||'UNICO',link_maps:mapsLink(p),anti_fake_score:antiFakeScore(p)}}
export function similarity(a,b){let s=0;const aa=money(a.area_terreno_m2),bb=money(b.area_terreno_m2),pa=money(a.preco),pb=money(b.preco);if(normalizeText(a.cidade)===normalizeText(b.cidade))s+=10;if(normalizeText(a.bairro)===normalizeText(b.bairro))s+=15;if(normalizeText(a.logradouro)===normalizeText(b.logradouro))s+=20;if(a.numero&&b.numero&&String(a.numero)===String(b.numero))s+=30;if(aa&&bb&&Math.abs(aa-bb)/Math.max(aa,bb)<=.05)s+=20;if(pa&&pb&&Math.abs(pa-pb)/Math.max(pa,pb)<=.10)s+=10;if(a.foto_hash&&b.foto_hash&&a.foto_hash===b.foto_hash)s+=60;return Math.min(s,100)}
export function deduplicate(list){const out=[];const links=[];for(const p0 of list){const p=canonicalize(p0,out.length);let merged=false;for(const x of out){const score=similarity(p,x);if(score>=70){x.origens=[...(x.origens||[x.portal]),p.portal].filter(Boolean);x.historico_precos=[...(x.historico_precos||[{preco:x.preco,url:x.url,data:x.data_consulta}]),{preco:p.preco,url:p.url,data:p.data_consulta}];links.push({a:x.id_canonico,b:p.id_canonico,score,status:'MESCLADO'});merged=true;break}else if(score>=45){links.push({a:x.id_canonico,b:p.id_canonico,score,status:'PROVAVEL'})}}if(!merged)out.push(p)}return {unique:out,links}}
export function antiFakeScore(p){let s=0;if(!p.url)s+=20;if(!p.logradouro&&!p.numero)s+=15;if(!p.codigo)s+=10;if(p.urgencia_suspeita)s+=20;if(p.pede_sinal_antes_visita)s+=35;return Math.min(s,100)}
export function modeA(p,params={}){const At=money(p.area_terreno_m2);const ca=money(p.ca_max||params.ca_max);const ac=At*ca;const eff=Math.min(.78,Math.max(.68,money(params.eficiencia||.72)));const apv=ac*eff;const vgv=apv*money(params.preco_venda_m2);const oodc=money(params.oodc);const land=money(p.preco);return {At,ca_max:ca,AC:ac,eficiencia:eff,APV:apv,VGV:vgv,OODC:oodc,preco_potencial_m2:ac?(land+oodc)/ac:0,custo_terreno_outorga_vgv:vgv?(land+oodc)/vgv:0}}
export function modeBC(p,params={}){const rent=money(p.aluguel||params.aluguel);const annual=rent*12;const adm=annual*money(params.adm_pct||.09);const vac=annual*money(params.vacancia_pct||.05);const maint=annual*money(params.manutencao_pct||.03);const insurance=money(params.seguro_anual);const condo=money(p.condominio)*12*money(params.condominio_vago_pct||0);const iptu=money(p.iptu)*12;const inad=annual*money(params.inadimplencia_pct||.02);const noi=annual-iptu-condo-maint-insurance-vac-inad-adm;const price=money(p.preco);return {aluguel_mensal:rent,yield_bruto:price?annual/price:0,NOI:noi,cap_rate_liquido:price?noi/price:0,payback_anos:noi>0?price/noi:null,valor_total_ocupacao:rent+money(p.condominio)+money(p.iptu)}}
export const CHECKS=['Briefing confirmado e modo definido','≥12 portais pesquisados e documentados','Modo A: fontes oficiais/zoneamento e potencial preenchidos ou limitação registrada','Áreas de terreno diferenciadas e confrontadas quando possível','Deduplicação executada e histórico de preços preservado','geo_precisao + link anúncio + Google Maps','Filtro anti-fake e frescor aplicados','Excel XLSX gerado','Relatório executivo gerado','Limitações declaradas; fato × inferência separados','B/C: cap rate líquido e yield separados'];
